import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const rubikFont = localFont({
  src: "../fonts/RubikMoonrocks-Regular.ttf",
  variable: "--font-rubik",
  weight: "400",
  style: "normal",
  display: "swap",
  fallback: ["Arial", "Helvetica", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
